---
# Ansible collections required for this repository
# Note: ansible.builtin is not listed as it's included with ansible-core
collections:
  - name: ansible.posix
    version: ">=1.3.0"

  - name: community.general
    version: ">=10.3.0"  # Required for proxmox_pct_remote connection plugin

  - name: community.proxmox
    version: ">=1.4.0"  # Better proxmox_pct_remote implementation

  - name: community.docker
    version: ">=3.0.0"
