"""Pytest fixtures for E2E pipeline tests."""

import json
import os
import socket
from pathlib import Path

import pytest


@pytest.fixture(scope="session")
def terraform_inventory():
    """Load terraform inventory from JSON file.

    Returns the full inventory dict from inventory/terraform_inventory.json.
    The file is generated by terraform-proxmox and must exist before running
    E2E tests.
    """
    inventory_path = (
        Path(__file__).resolve().parents[2] / "inventory" / "terraform_inventory.json"
    )
    if not inventory_path.exists():
        pytest.skip(
            f"Terraform inventory not found at {inventory_path}. "
            "Generate it with: cd ~/git/terraform-proxmox/main && "
            "terragrunt output -json ansible_inventory > "
            "~/git/ansible-proxmox-apps/main/inventory/terraform_inventory.json"
        )
    with open(inventory_path) as f:
        return json.load(f)


@pytest.fixture(scope="session")
def constants(terraform_inventory):
    """Return the constants dict from terraform inventory.

    Contains service_ports, syslog_ports, netflow_ports, and
    notification_ports as defined in terraform-proxmox locals.tf.
    """
    if "constants" not in terraform_inventory:
        pytest.skip("Inventory missing 'constants' section")
    return terraform_inventory["constants"]


@pytest.fixture(scope="session")
def haproxy_host(terraform_inventory):
    """Return the HAProxy container IP from inventory."""
    return terraform_inventory["containers"]["haproxy"]["ip"]


@pytest.fixture(scope="session")
def docker_host_ip(terraform_inventory):
    """Return the Docker Swarm host IP from inventory."""
    return terraform_inventory["docker_vms"]["docker-host"]["ip"]


@pytest.fixture(scope="session")
def splunk_host(terraform_inventory):
    """Return the Splunk VM IP from inventory."""
    return terraform_inventory["splunk_vm"]["splunk"]["ip"]


@pytest.fixture(scope="session")
def splunk_creds(terraform_inventory, constants):
    """Return Splunk credentials as (mgmt_url, user, password).

    The management URL is built from the Splunk VM IP and the splunk_mgmt
    port in terraform constants. The password comes from the SPLUNK_PASSWORD
    environment variable.
    """
    splunk_ip = terraform_inventory["splunk_vm"]["splunk"]["ip"]
    mgmt_port = constants["service_ports"]["splunk_mgmt"]
    password = os.environ.get("SPLUNK_PASSWORD")
    if not password:
        pytest.skip("SPLUNK_PASSWORD environment variable not set")
    mgmt_url = f"https://{splunk_ip}:{mgmt_port}"
    return (mgmt_url, "admin", password)


@pytest.fixture(scope="session", autouse=True)
def infrastructure_reachable(docker_host_ip):
    """Skip all tests if the Docker Swarm host is unreachable.

    Attempts a TCP connection to port 22 (SSH) on the docker-host with
    a 5-second timeout. If the host is unreachable, all E2E tests are
    skipped since the pipeline infrastructure is not available.
    """
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(5)
    try:
        sock.connect((docker_host_ip, 22))
        sock.close()
    except (socket.timeout, ConnectionRefusedError, OSError):
        pytest.skip(
            f"Infrastructure unreachable: cannot connect to "
            f"{docker_host_ip}:22 (docker-host SSH)"
        )
