---
all:
  hosts:
    cribl_edge_1:
      ansible_host: "{{ lookup('env', 'CRIBL_EDGE_1') }}"
    cribl_edge_2:
      ansible_host: "{{ lookup('env', 'CRIBL_EDGE_2') }}"
    cribl_stream:
      ansible_host: "{{ lookup('env', 'CRIBL_STREAM') }}"
    haproxy:
      ansible_host: "{{ lookup('env', 'HAPROXY') }}"
    splunk_vm:
      ansible_host: "{{ lookup('env', 'SPLUNK_VM') }}"

  children:
    cribl_edge:
      hosts:
        cribl_edge_1:
        cribl_edge_2:

    cribl_stream_group:
      hosts:
        cribl_stream:

    haproxy_group:
      hosts:
        haproxy:

    splunk:
      hosts:
        splunk_vm:

  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
