---
all:
  hosts:
    # LXC Containers - use proxmox_pct_remote connection (no SSH needed)
    # ansible_host should be the Proxmox host for pct_remote connections
    cribl_edge_01:
      ansible_host: 10.0.1.180
      ansible_connection: ssh
      ansible_user: root
      ansible_ssh_private_key_file: /Users/jevans/.ssh/id_rsa_pve
      hostname: cribl-edge-01
    cribl_edge_02:
      ansible_host: 10.0.1.181
      ansible_connection: ssh
      ansible_user: root
      ansible_ssh_private_key_file: /Users/jevans/.ssh/id_rsa_pve
      hostname: cribl-edge-02
    cribl_stream_01:
      ansible_pct_vmid: 182
      ansible_host: pve.jacobpevans.com
      hostname: cribl-stream-01
    haproxy:
      ansible_pct_vmid: 175
      ansible_host: pve.jacobpevans.com
      hostname: haproxy

    # VMs - use standard SSH connection
    splunk:
      ansible_host: 10.0.1.200
      ansible_connection: ssh
      ansible_user: debian
      hostname: splunk

  children:
    # LXC containers group - all use pct_remote connection
    lxc_containers:
      hosts:
        cribl_edge_01:
        cribl_edge_02:
        cribl_stream_01:
        haproxy:
      vars:
        ansible_connection: community.general.proxmox_pct_remote
        ansible_pct_host: pve.jacobpevans.com
        ansible_pct_user: root
        ansible_pct_private_key_file: /Users/jevans/.ssh/id_rsa_pve
        ansible_user: root

    cribl_edge:
      hosts:
        cribl_edge_01:
        cribl_edge_02:

    cribl_stream_group:
      hosts:
        cribl_stream_01:

    haproxy_group:
      hosts:
        haproxy:
          ansible_pct_vmid: 175
      vars:
        ansible_connection: community.general.proxmox_pct_remote
        ansible_pct_host: pve.jacobpevans.com
        ansible_pct_user: root
        ansible_pct_private_key_file: /Users/jevans/.ssh/id_rsa_pve
        ansible_user: root

    splunk_group:
      hosts:
        splunk:

  vars:
    ansible_python_interpreter: /usr/bin/python3
    proxmox_domain: jacobpevans.com
