---
all:
  hosts:
    # LXC Containers - use proxmox_pct_remote connection (no SSH needed)
    # ansible_host should be the Proxmox host for pct_remote connections
    cribl_edge_01:
      proxmox_vmid: 180
      ansible_host: "{{ lookup('env', 'PROXMOX_VE_HOSTNAME') }}"
      hostname: cribl-edge-01
    cribl_edge_02:
      proxmox_vmid: 181
      ansible_host: "{{ lookup('env', 'PROXMOX_VE_HOSTNAME') }}"
      hostname: cribl-edge-02
    cribl_stream_01:
      proxmox_vmid: 182
      ansible_host: "{{ lookup('env', 'PROXMOX_VE_HOSTNAME') }}"
      hostname: cribl-stream-01
    haproxy:
      proxmox_vmid: 175
      ansible_host: "{{ lookup('env', 'PROXMOX_VE_HOSTNAME') }}"
      hostname: haproxy
    apt_cacher:
      ansible_pct_vmid: 106
      ansible_host: "{{ lookup('env', 'PROXMOX_VE_HOSTNAME') }}"
      hostname: apt-cacher

  children:
    # LXC containers group - all use pct_remote connection
    lxc_containers:
      hosts:
        cribl_edge_01:
        cribl_edge_02:
        cribl_stream_01:
        haproxy:
        apt_cacher:
      vars:
        ansible_connection: community.general.proxmox_pct_remote
        ansible_pct_host: "{{ lookup('env', 'PROXMOX_VE_HOSTNAME') }}"
        ansible_pct_user: root
        ansible_pct_private_key_file: "{{ lookup('env', 'PROXMOX_SSH_KEY_PATH') }}"
        ansible_pct_node: "{{ lookup('env', 'PROXMOX_VE_NODE') }}"

    cribl_edge:
      hosts:
        cribl_edge_01:
        cribl_edge_02:

    cribl_stream_group:
      hosts:
        cribl_stream_01:

    haproxy_group:
      hosts:
        haproxy:

    apt_cacher_group:
      hosts:
        apt_cacher:

    # splunk_group is dynamically created by load_terraform.yml
    # DO NOT add splunk hosts here - they come from Terraform state

  vars:
    ansible_python_interpreter: /usr/bin/python3
    proxmox_domain: "{{ lookup('env', 'PROXMOX_DOMAIN') }}"
