---
all:
  hosts:
    # LXC Containers - use proxmox_pct_remote connection (no SSH needed)
    # VM IDs from Doppler (CRIBL_EDGE_1_VMID, etc.)
    cribl_edge_01:
      ansible_pct_vmid: "{{ lookup('env', 'CRIBL_EDGE_1_VMID') }}"
      hostname: cribl-edge-01
    cribl_edge_02:
      ansible_pct_vmid: "{{ lookup('env', 'CRIBL_EDGE_2_VMID') }}"
      hostname: cribl-edge-02
    cribl_stream_01:
      ansible_pct_vmid: "{{ lookup('env', 'CRIBL_STREAM_VMID') }}"
      hostname: cribl-stream-01
    haproxy:
      ansible_pct_vmid: "{{ lookup('env', 'HAPROXY_VMID') }}"
      hostname: haproxy

    # VMs - use standard SSH connection
    splunk:
      ansible_host: "{{ lookup('env', 'SPLUNK_VM') }}"
      ansible_connection: ssh
      ansible_user: debian
      hostname: splunk

  children:
    # LXC containers group - all use pct_remote connection
    lxc_containers:
      hosts:
        cribl_edge_01:
        cribl_edge_02:
        cribl_stream_01:
        haproxy:
      vars:
        ansible_connection: community.general.proxmox_pct_remote
        ansible_pct_host: "{{ lookup('env', 'PROXMOX_VE_HOSTNAME') }}"
        ansible_pct_user: root
        ansible_pct_private_key_file: "{{ lookup('env', 'PROXMOX_SSH_KEY_PATH') }}"
        ansible_user: root

    cribl_edge:
      hosts:
        cribl_edge_01:
        cribl_edge_02:

    cribl_stream_group:
      hosts:
        cribl_stream_01:

    haproxy_group:
      hosts:
        haproxy:

    splunk_group:
      hosts:
        splunk:

  vars:
    ansible_python_interpreter: /usr/bin/python3
    internal_domain: "{{ lookup('env', 'INTERNAL_DOMAIN') }}"
