---
all:
  hosts:
    # LXC Containers - use proxmox_pct_remote connection (no SSH needed)
    # IPs derived from: first 3 octets of PROXMOX_VE_GATEWAY + vmid
    # Example: PROXMOX_VE_GATEWAY=10.0.1.1 + vmid=180 → 10.0.1.180
    cribl_edge_01:
      ansible_pct_vmid: 180
      ansible_host: "{{ lookup('env', 'PROXMOX_VE_GATEWAY').rsplit('.', 1)[0] }}.180"
      hostname: cribl-edge-01
    cribl_edge_02:
      ansible_pct_vmid: 181
      ansible_host: "{{ lookup('env', 'PROXMOX_VE_GATEWAY').rsplit('.', 1)[0] }}.181"
      hostname: cribl-edge-02
    cribl_stream_01:
      ansible_pct_vmid: 182
      ansible_host: "{{ lookup('env', 'PROXMOX_VE_GATEWAY').rsplit('.', 1)[0] }}.182"
      hostname: cribl-stream-01
    haproxy:
      ansible_pct_vmid: 175
      ansible_host: "{{ lookup('env', 'PROXMOX_VE_GATEWAY').rsplit('.', 1)[0] }}.175"
      hostname: haproxy

    # VMs - use standard SSH connection
    # IP derived from: first 3 octets of PROXMOX_VE_GATEWAY + vmid
    splunk:
      ansible_host: "{{ lookup('env', 'PROXMOX_VE_GATEWAY').rsplit('.', 1)[0] }}.200"
      ansible_connection: ssh
      ansible_user: debian
      hostname: splunk

  children:
    # LXC containers group - all use pct_remote connection
    lxc_containers:
      hosts:
        cribl_edge_01:
        cribl_edge_02:
        cribl_stream_01:
        haproxy:
      vars:
        ansible_connection: community.general.proxmox_pct_remote
        ansible_pct_host: "{{ lookup('env', 'PROXMOX_VE_HOSTNAME') }}"
        ansible_pct_user: root
        ansible_pct_private_key_file: "{{ lookup('env', 'PROXMOX_SSH_KEY_PATH') }}"
        ansible_user: root

    cribl_edge:
      hosts:
        cribl_edge_01:
        cribl_edge_02:

    cribl_stream_group:
      hosts:
        cribl_stream_01:

    haproxy_group:
      hosts:
        haproxy:

    splunk_group:
      hosts:
        splunk:

  vars:
    ansible_python_interpreter: /usr/bin/python3
    proxmox_domain: "{{ lookup('env', 'PROXMOX_DOMAIN') }}"
