---
# Pre-playbook that loads Terraform infrastructure data dynamically
# This playbook runs first to populate the Ansible inventory from Terraform outputs,
# eliminating hardcoded VM IDs and IPs from Ansible configuration.
#
# It expects terraform_inventory.json to be present (generated via:
# terragrunt output -json ansible_inventory > inventory/terraform_inventory.json)

- name: Load Terraform Infrastructure Inventory
  hosts: localhost
  become: false
  gather_facts: false
  tags: always

  vars:
    # Override global ansible_become for localhost tasks
    ansible_become: false

  tasks:
    - name: Verify terraform inventory exists
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/../inventory/terraform_inventory.json"
      register: terraform_inventory_check

    - name: Fail if terraform inventory is missing
      ansible.builtin.fail:
        msg: |
          terraform_inventory.json not found!

          Generate it by running from terraform-proxmox:
            terragrunt output -json ansible_inventory > \
              ~/git/ansible-proxmox-apps/main/inventory/terraform_inventory.json

          Or sync from existing deployment.
      when: not terraform_inventory_check.stat.exists

    - name: Load Terraform inventory JSON
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../inventory/terraform_inventory.json"
        name: terraform_data

    - name: Load pipeline constants
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../inventory/pipeline_constants.json"
        name: pipeline_constants

    - name: Merge constants into terraform_data
      ansible.builtin.set_fact:
        terraform_data: >-
          {{ terraform_data | combine({'constants': pipeline_constants}) }}

    - name: Add LXC containers to inventory (proxmox_pct_remote connection)
      ansible.builtin.add_host:
        name: "{{ item.key }}"
        groups:
          - lxc_containers
          - all
        ansible_pct_vmid: "{{ item.value.vmid }}"
        ansible_host: "{{ item.value.ip }}"
        ansible_connection: "{{ item.value.ansible_connection }}"
        ansible_pct_host: "{{ lookup('env', 'PROXMOX_VE_HOSTNAME') }}"
        ansible_pct_user: root
        ansible_pct_private_key_file: "{{ lookup('env', 'PROXMOX_SSH_KEY_PATH') }}"
        hostname: "{{ item.value.hostname }}"
        ansible_pct_node: "{{ item.value.node }}"
        host_tags: "{{ item.value.tags | default([]) }}"
      loop: "{{ terraform_data.containers | dict2items }}"
      when:
        - terraform_data.containers is defined
        - terraform_data.containers | length > 0

    - name: Add VMs to inventory (SSH connection)
      ansible.builtin.add_host:
        name: "{{ item.key }}"
        groups:
          - vms
          - all
        ansible_host: "{{ item.value.ip }}"
        ansible_connection: "{{ item.value.ansible_connection }}"
        ansible_user: debian
        ansible_ssh_private_key_file: "{{ lookup('env', 'PROXMOX_SSH_KEY_PATH') }}"
        hostname: "{{ item.value.hostname }}"
        host_tags: "{{ item.value.tags | default([]) }}"
      loop: "{{ terraform_data.vms | dict2items }}"
      when:
        - terraform_data.vms is defined
        - terraform_data.vms | length > 0

    - name: Add Splunk VM to inventory (SSH connection)
      ansible.builtin.add_host:
        name: splunk
        groups:
          - splunk_group
          - splunk_vms
          - all
        ansible_host: "{{ terraform_data.splunk_vm.splunk.ip }}"
        ansible_connection: "{{ terraform_data.splunk_vm.splunk.ansible_connection }}"
        ansible_user: debian
        ansible_ssh_private_key_file: "{{ lookup('env', 'PROXMOX_SSH_KEY_PATH') }}"
        hostname: "{{ terraform_data.splunk_vm.splunk.hostname }}"
        vmid: "{{ terraform_data.splunk_vm.splunk.vmid }}"
      when: terraform_data.splunk_vm.splunk is defined

    - name: Add Docker VMs to inventory (SSH connection for Cribl Swarm hosts)
      ansible.builtin.add_host:
        name: "{{ item.key }}"
        groups:
          - docker_vms
          - cribl_docker_group
          - all
        ansible_host: "{{ item.value.ip }}"
        ansible_connection: "{{ item.value.ansible_connection }}"
        ansible_user: debian
        ansible_ssh_private_key_file: "{{ lookup('env', 'PROXMOX_SSH_KEY_PATH') }}"
        hostname: "{{ item.value.hostname }}"
        vmid: "{{ item.value.vmid }}"
        host_tags: "{{ item.value.tags | default([]) }}"
      loop: "{{ terraform_data.docker_vms | dict2items }}"
      when:
        - terraform_data.docker_vms is defined
        - terraform_data.docker_vms | length > 0
