---
llamaindex_data_dir: /opt/llamaindex
llamaindex_ollama_model: "nomic-embed-text"
llamaindex_qdrant_host: "{{ hostvars['qdrant']['ansible_host'] }}"
llamaindex_qdrant_port: "{{ hostvars['localhost']['terraform_data']['constants']['vector_db_ports']['qdrant_http'] }}"
llamaindex_qdrant_api_key: "{{ lookup('env', 'QDRANT_API_KEY') }}"
